# 這個 Workflow 的名稱
name: 雪拼 CI

# 觸發條件：當推送到 main 分支，或對 main 分支發起 Pull Request 時觸發
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 工作流程執行的內容
jobs:
  # 我們定義一個叫做 build-and-test 的工作
  build-and-test:
    # 指定這個工作要在最新的 Ubuntu 環境上執行
    runs-on: ubuntu-latest

    # 這個工作的執行步驟
    steps:
      # 步驟一：把你的程式碼從 GitHub repo 拉下來
      - name: Checkout 專案原始碼
        uses: actions/checkout@v4

      # 步驟二：安裝 pnpm (它會自動讀取 package.json 的版本)
      - name: 安裝 pnpm
        uses: pnpm/action-setup@v4
        # with: ... 那段已經被我們刪掉了！

      # 步驟三：安裝 Node.js 環境
      - name: 設定 Node.js 環境
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 建議使用 LTS 版本
          cache: 'pnpm' # 啟用快取，讓下次安裝依賴更快

      # 步驟四：安裝所有專案依賴
      - name: 安裝依賴套件
        run: pnpm install

      # 步驟五：執行程式碼風格檢查 (Lint)
      - name: 檢查程式碼風格 (ESLint)
        run: pnpm --filter "./apps/*" lint

      # 步驟六：建置所有專案 (Build)
      - name: 建置專案 (Build)
        run: pnpm build
